storage: ../storage
auth:
  htpasswd:
    file: .htpasswd
    algorithm: bcrypt
    rounds: 10
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
packages:
  '@*/*':
    access: $all
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
log: { type: stdout, format: pretty, level: http }
